Add ML coupling
DataWaveProject/CAM pull request #14
Opened 2024-08-06 09:47 UTC by jatkinson1000

This PR adds a coupling routine that calls the neural net to close #13 

It is currently WIP.

2024-11-05 08:26 UTC, jatkinson1000 commented
Before merging need to:

- [ ] Update docs to point at correct branch (`datawave_ml`, not `coupling`).

2025-01-31 18:36 UTC, ma595 commented
As @jatkinson1000 mentioned above, there are a few mismatches with branch names.

2025-05-20 18:16 UTC, ma595 requested changes
Just a quick summary: 

- Stepped through README and built and executed code without much trouble. 
- Executed and debugged on Derecho with and without `gw_convect_dp_ml = .true.`.   
- Increased memory requirement to 235GB - this brought some more stability.

I have highlighted a few things relating to documentation. There are also a few outstanding TODOs which might need to be removed? 

In terms of code changes, I don't thing there is much at all to do. It would be nice to have a few runtime checks on the arrays passed to `gw_ml.F90`, but this is a nitpick.

Speaking of nitpicks, what is the English convention for CAM / CESM? American or British?

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
> +      'V tendency due to convective gravity wave drag from NN.')
This comment looks incorrect

2025-05-20 18:16 UTC, ma595 commented on bld/namelist_files/namelist_definition.xml
>    Whether or not to run a piggybacking comparison of the ML deep convection gravity
On L1418, :as dictacted by `gw_convect_deep_ml`, looks like this comment is incorrect (I'm not allowed to comment on unmodified lines).

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
> +      'V tendency due to convective gravity wave drag from NN.')
should be "V tendency due to convective gravity wave drag from BERES"?

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
> +
Is the normalisation procedure documented anywhere - the README explains these variables but what is the larger context for this? Perhaps this has been discussed offline, so any further documentation is redundant? 

I suppose it is simply that `gw_convect_dp_ml_norms` contains statistics (means, stds) to normalise the inputs and outpus consistently? `net_path` is obvious. Might be worth documenting in any case?

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
> +       'Brunt Vaisala Frequency')
I don't know anything about these. Frequency doesn't have J/kg - should be 1/s?  Looks like a copy error from the previous line.

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
> +     ! TODO: If we are running with the ML scheme save tau to a temp variable so we
I don't fully understand this, but I presume it will make sense to future developers.

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_drag.F90
There are still some TODOs in gw_drag.F90 that haven't been addressed. i.e. egwdffi, qtgw ttgw.

2025-05-20 18:16 UTC, ma595 commented on bld/namelist_files/namelist_definition.xml
Minor fixes to comments needed.

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  do i = 1, ncol
I just realised that we're not actually doing batching here. Is this possible with FTorch?

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  do i = 1, ncol
i.e. a 2D array is collected in advance. Traditionally wouldn't this be fed batch wise into the NN?

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +
Generally there could be more detailed docstrings or public facing documentation on what the code does. Consider adding more to the top of the file and to other docstrings.

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  ! expected by the NN, and concatenate into a single input tensor as expected by the NN.
It might be worth spelling out that each variable is stacked (all u, then all v, etc for each column). THe overall shape of the data to the NN is `[input_dim, batch_size]` where `input_dim = 8 * pver + 4`, and batch_size = ncol`. 

Could have this as a comment in the normalise_data function? 

```
! For each atmospheric column (i = 1 to ncol), we construct a single input vector for the neural network
! by stacking all values of each variable in the following order:
```

2025-05-20 18:16 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  ! Column dimension.
I think this routine is missing some runtime checks on expected input shapes. 

Could we validate the data dimensions of data coming from CAM? i.e. sizes and shapes are consistent with what we expect ncol to be, for example. Perhaps these checks are done elsewhere?

2025-05-21 10:17 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +
These values came from Qiang and is simply a mean and std deviation scaling.
There is an explanation on line 383 of `gw_ml.F90` but I can add more if you want.

Longer term we agreed with Pedram that this process should be a static layer of the net rather than done outside.

2025-05-21 10:30 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +     ! TODO: If we are running with the ML scheme save tau to a temp variable so we
IIRC this was because we use `tau` throughout the code after the drag scheme, but it is calculated in `gw_beres_src()`. I think if piggybacking I was worried that it would get updated in the call to the beres scheme and then passed to the ML scheme.

I can remove this for now if you want as it seems a lower concern?

2025-05-21 10:34 UTC, jatkinson1000 commented on src/physics/cam/gw_ml.F90
> +  do i = 1, ncol
Yes, when writing this we thought batching was not possible from the Fortran.
However, Tom suggests this is possible with Aman's code.

If you can try this we could add it here.

2025-05-21 10:35 UTC, jatkinson1000 commented on src/physics/cam/gw_ml.F90
> +  ! Column dimension.
It is being passed from the main CAM as an `intent(in)` so I'm not quite sure I understand.

2025-05-21 11:30 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  ! Column dimension.
OK, ignore this request. I was thinking of adding some runtime checks on shape or physical consistency - but given this has already passed throughg CAM  it probably isn't necessary here. 

Should we add any checks on

2025-05-21 11:31 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  ! Column dimension.
Would it be worth adding runtime checks on the output (dimension, values or otherwise) of the NN?

2025-05-21 11:38 UTC, ma595 commented on src/physics/cam/gw_ml.F90
> +  ! Column dimension.
We could initialise net_outputs to be zero and then check if they're still zero after running the loop? There are probably more things we could do but this wouldn't be a bad first check.

2025-05-21 12:12 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +     ! TODO: If we are running with the ML scheme save tau to a temp variable so we
@ma595 suggests making a comment to note what is happening and remove the TODO

2025-05-21 12:45 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +      'V tendency due to convective gravity wave drag from NN.')
Yes, addressed in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

2025-05-21 12:45 UTC, jatkinson1000 commented on bld/namelist_files/namelist_definition.xml
>    Whether or not to run a piggybacking comparison of the ML deep convection gravity
It is correct, but I can see how it is unclear. Have made more explicit in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

2025-05-21 12:45 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +       'Brunt Vaisala Frequency')
I have amended to `'frequency'` which CAM uses for other frequency fields in output in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

2025-05-21 12:45 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
> +     ! TODO: If we are running with the ML scheme save tau to a temp variable so we
Done this in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

2025-05-21 12:49 UTC, jatkinson1000 commented on src/physics/cam/gw_drag.F90
Removed now in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869 and https://github.com/DataWaveProject/CAM/pull/14/commits/e83db09660db77a07084b3b5d25b2e1dd894ae20

2025-05-21 12:49 UTC, jatkinson1000 commented on bld/namelist_files/namelist_definition.xml
Think this is captured in a specific comment below?

2025-05-21 12:50 UTC, jatkinson1000 commented on src/physics/cam/gw_ml.F90
> +  do i = 1, ncol
As discussed with @ma595, we will not do this as it requires further modification and testing.
We will leave a note in the report that this could be explored in future.

2025-05-21 12:51 UTC, jatkinson1000 commented on src/physics/cam/gw_ml.F90
> +
I have worked to do this for all subroutines in this file in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

Let me know what you think.

2025-05-21 12:51 UTC, jatkinson1000 commented on src/physics/cam/gw_ml.F90
> +  ! expected by the NN, and concatenate into a single input tensor as expected by the NN.
Thanks, I have incorporated this in https://github.com/DataWaveProject/CAM/pull/14/commits/2228b62038a8f8ec96ab224835eab7a9235f4869

2025-05-21 12:56 UTC, jatkinson1000 commented
Rebased on `datawave_ml` and updated docs to ensure we point to correct branch after merging.

2025-05-22 09:48 UTC, ma595 commented on bld/namelist_files/namelist_definition.xml
>    Whether or not to run a piggybacking comparison of the ML deep convection gravity
Shouldn't it be `gw_convect_dp_ml` instead of deep?

2025-05-22 09:52 UTC, ma595 commented
Before merging I will do a runtime check on the output of the neural network

2025-05-22 13:52 UTC, jatkinson1000 commented on bld/namelist_files/namelist_definition.xml
>    Whether or not to run a piggybacking comparison of the ML deep convection gravity
Good catch! Fixed in https://github.com/DataWaveProject/CAM/pull/14/commits/95f757fc3754ec628d8109b52caa772179f5308b

2025-05-23 12:29 UTC, ma595 commented
One final check:

```
./create_newcase --case ~/jobs/CAM_GW-ML_TEST_RELEASE --compset FMTHIST --res ne30pg3_ne30pg3_mg17 --project URIC0009 --machine derecho
cd /glade/u/home/matta/jobs/CAM_GW-ML_TEST_RELEASE
./case.setup
# copy pre-existing file
cp ./debug_CAM_GW-ML_LONG_ML_DRIVE_RELEASE/user_nl_cam ./CAM_GW-ML_TEST_RELEASE
./case.build
./case.submit
```

2025-05-23 14:40 UTC, ma595 approved these changes

2025-05-23 14:44 UTC, jatkinson1000 commented
This code has now been used to run 3-year simulations with both the original physics-based scheme and the coupled ML scheme for convective gravity wave sources.

Documentation for running, and how the code was developed, is provided in the README, and in a longer report to the collaborators.

Will shortly merge into main, thanks to all who worked on this.

 @yqsun91 @phz-fluids @ma595 @omarjamil

2025-05-23 14:45 UTC, merged